# Generated by Django 6.0.4 on 2026-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_bookmarked_news'),
        ('articles', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bookmarked_articles',
            field=models.ManyToManyField(blank=True, to='articles.article', verbose_name='Статьи в закладках'),
        ),
    ]
