# Generated by Django 6.0.4 on 2026-04-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0006_annotation_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotmodel3d',
            name='init_pos_x',
            field=models.FloatField(default=0, help_text='Смещение по оси X после авто-центрирования (единицы сцены, модель ~100 ед.)', verbose_name='Позиция X'),
        ),
        migrations.AddField(
            model_name='robotmodel3d',
            name='init_pos_y',
            field=models.FloatField(default=0, help_text='Смещение по оси Y (вертикаль)', verbose_name='Позиция Y'),
        ),
        migrations.AddField(
            model_name='robotmodel3d',
            name='init_pos_z',
            field=models.FloatField(default=0, help_text='Смещение по оси Z (глубина)', verbose_name='Позиция Z'),
        ),
        migrations.AddField(
            model_name='robotmodel3d',
            name='init_rot_y',
            field=models.FloatField(default=0, help_text='Поворот модели вокруг вертикальной оси в градусах (0 = как в файле)', verbose_name='Поворот Y (°)'),
        ),
    ]
