# Generated by Django 6.0.4 on 2026-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0007_robotmodel3d_init_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotmodel3d',
            name='init_scale',
            field=models.FloatField(default=1.0, help_text='Дополнительный множитель масштаба поверх авто-нормализации (1.0 = без изменений)', verbose_name='Масштаб'),
        ),
    ]
